"""role exclusivity metadata

Revision ID: decb75b3de6b
Revises: 9e1a2b3c4d5e
Create Date: 2025-12-26 16:05:00.694840

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "decb75b3de6b"
down_revision: str | None = "9e1a2b3c4d5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("is_system", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("roles", sa.Column("exclusive_group", sa.String(length=64), nullable=True))
    op.add_column(
        "roles",
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.create_index(op.f("ix_roles_exclusive_group"), "roles", ["exclusive_group"], unique=False)
    op.create_index(op.f("ix_roles_is_system"), "roles", ["is_system"], unique=False)
    op.create_index(op.f("ix_roles_priority"), "roles", ["priority"], unique=False)
    # ### end Alembic commands ###

    # Seed system role metadata for mutual exclusivity within the "account" group.
    op.execute(
        sa.text(
            "UPDATE roles SET is_system = true, exclusive_group = 'account', priority = 100 "
            "WHERE name = 'admin'"
        )
    )
    op.execute(
        sa.text(
            "UPDATE roles SET is_system = true, exclusive_group = 'account', priority = 10 "
            "WHERE name = 'user'"
        )
    )

    # Backward compatibility cleanup:
    # If a user has both 'admin' and 'user', keep only 'admin' (remove 'user').
    op.execute(
        sa.text(
            """
            DELETE FROM user_roles ur
            USING roles r_user
            WHERE ur.role_id = r_user.id
              AND r_user.name = 'user'
              AND EXISTS (
                SELECT 1
                FROM user_roles ur2
                JOIN roles r_admin ON ur2.role_id = r_admin.id
                WHERE ur2.user_id = ur.user_id
                  AND r_admin.name = 'admin'
              )
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roles_priority"), table_name="roles")
    op.drop_index(op.f("ix_roles_is_system"), table_name="roles")
    op.drop_index(op.f("ix_roles_exclusive_group"), table_name="roles")
    op.drop_column("roles", "priority")
    op.drop_column("roles", "exclusive_group")
    op.drop_column("roles", "is_system")
    # ### end Alembic commands ###
